### ISSUE TITLE
Use TestContainer for MySQL based tests

### ISSUE THREAD

**Issue by anantdamle** [GoogleCloudPlatform/auto-data-tokenize#25]
**Context:** Current JDBC based unit tests use in-memory MariaDB library

**Challenges:** 
  1.  MariaDB is not a true MySQL representation
  1.  Limits  the types of databases that can be checked for integration testing
  1.  requires system level dependencies `libncurses5`

**Proposed Solution:** Use [TestContainers database modules](https://www.testcontainers.org/modules/databases/) to spin up database containers to testing.

**Comment by trance1st** [comment]
Hello @anantdamle,
I would like to work on this. Can you assign me please?

**Comment by anantdamle** [comment]
@trance1st thanks for expressing interest, can you read through [CONTRIBUTING](https://github.com/GoogleCloudPlatform/auto-data-tokenize/blob/main/CONTRIBUTING.md) guidelines and propose a PR, happy to review the PR.

**Comment by posabogdanpetre** [comment]
Hello @anantdamle,
Had to create another account (some problems signing the cla with the previous account).
https://github.com/GoogleCloudPlatform/auto-data-tokenize/pull/30
Can you please have a look?
