### ISSUE TITLE
Option to scan entire table for Cloud Data Loss Prevention and Dataflow

### ISSUE THREAD

**Issue by jingcyang3** [GoogleCloudPlatform/auto-data-tokenize#55]
For Cloud Data Loss Prevention and Dataflow solution on this page: https://cloud.google.com/architecture/automatically-apply-sensitivity-tags-in-data-catalog

Would be helpful to also have the option to scan entire database table.

**Comment by anantdamle** [comment]
It's already implemented.
use `--sampleSize=0`
